name: Nightly Build 🌙🛠️

on:
  push:
    paths:
      - .github/workflows/nightly.yml
      - src/**
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - dotnet-runtime: win-x64
            rust-target: x86_64-pc-windows-msvc
          - dotnet-runtime: win-arm64
            rust-target: aarch64-pc-windows-msvc
          - dotnet-runtime: linux-x64
            rust-target: x86_64-unknown-linux-gnu
          - dotnet-runtime: linux-arm64
            rust-target: aarch64-unknown-linux-gnu
          - dotnet-runtime: osx-arm64
            rust-target: aarch64-apple-darwin
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: true
          persist-credentials: false

      - uses: moonrepo/setup-rust@v1
        with:
          bins: cross
          channel: stable
          cache: false

      - if: matrix.rust-target == 'x86_64-pc-windows-msvc' || matrix.rust-target == 'aarch64-pc-windows-msvc'
        run: cargo build -r --target ${{ matrix.rust-target }}
        working-directory: src/WingetCreateCore/Common/Msi/rust-msi

      - if: matrix.rust-target != 'x86_64-pc-windows-msvc' && matrix.rust-target != 'aarch64-pc-windows-msvc'
        run: cross build -r --target ${{ matrix.rust-target }}
        working-directory: src/WingetCreateCore/Common/Msi/rust-msi

      - run: dotnet publish ./WingetCreateCLI.csproj -c Release -r ${{ matrix.dotnet-runtime }} --output ./output
        working-directory: src/WingetCreateCLI

      - if: matrix.dotnet-runtime != 'win-x64' && matrix.dotnet-runtime != 'win-arm64'
        run: mv src/WingetCreateCLI/output/WingetCreateCLI ./wingetcreate-${{ matrix.dotnet-runtime }}

      - if: matrix.dotnet-runtime == 'win-x64' || matrix.dotnet-runtime == 'win-arm64'
        run: mv src/WingetCreateCLI/output/WingetCreateCLI.exe ./wingetcreate-${{ matrix.dotnet-runtime }}.exe

      - name: Delete old release 🗑️
        run: |
          gh api repos/$GITHUB_REPOSITORY/git/refs/tags/nightly | jq -r '.object.sha' | grep -q $GITHUB_SHA && exit 0
          gh release delete nightly -y --cleanup-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: softprops/action-gh-release@v2
        with:
          name: Nightly release 🌙
          tag_name: nightly
          draft: false
          files: wingetcreate-*
          fail_on_unmatched_files: true
          token: ${{ secrets.GITHUB_TOKEN }}
